# Generated by Django 5.2.7 on 2025-10-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=255)),
                ('page_number', models.IntegerField()),
                ('article_id', models.CharField(max_length=50)),
                ('gujarati_text', models.TextField()),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('sentiment', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('dist_token', models.CharField(blank=True, max_length=100, null=True)),
                ('article_type', models.CharField(max_length=100)),
                ('article_category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='articles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
