# Generated by Django 5.2.7 on 2025-11-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='Dcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='Tcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='category_word',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='distict_word',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='govt_word',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='is_govt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='prabhag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='prabhag_ID',
            field=models.IntegerField(null=True),
        ),
    ]
