# Generated by Django 5.2.7 on 2025-11-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0002_articleinfo_dcode_articleinfo_tcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='cat_Id',
            field=models.IntegerField(null=True),
        ),
    ]
