# Generated by Django 5.1.6 on 2025-11-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocrapp", "0003_articleinfo_cat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleinfo",
            name="gujarati_title",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="articleinfo",
            name="sentiment_gravity",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="articleinfo",
            name="gujarati_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="articleinfo",
            name="page_number",
            field=models.IntegerField(null=True),
        ),
    ]
