# Generated by Django 5.2.7 on 2025-11-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0004_articleinfo_gujarati_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='govt_word_rule_based',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
