# Generated by Django 5.1.6 on 2025-11-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocrapp", "0005_articleinfo_govt_word_rule_based"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleinfo",
            name="is_govt_push_nic",
            field=models.BooleanField(default=False),
        ),
    ]
