# Generated by Django 5.2.7 on 2025-11-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0006_articleinfo_is_govt_push_nic'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='pdf_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
