# Generated by Django 5.2.7 on 2025-11-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0007_articleinfo_pdf_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
