# Generated by Django 5.2.9 on 2025-12-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0008_articleinfo_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='is_connect_test',
            field=models.BooleanField(default=False),
        ),
    ]
