# Generated by Django 5.2.9 on 2025-12-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0009_articleinfo_is_connect_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
