# Generated by Django 5.2.9 on 2025-12-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0010_articleinfo_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='is_govt_llm',
            field=models.BooleanField(default=False),
        ),
    ]
