# Generated by Django 5.2.9 on 2025-12-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0011_articleinfo_is_govt_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='duplicate_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='is_govt_llm_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
