# Generated by Django 5.2.9 on 2025-12-23 17:18

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0012_articleinfo_duplicate_id_articleinfo_is_duplicate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
