# Generated by Django 5.2.9 on 2026-01-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0013_articleinfo_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='extra_flag_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='extra_flag_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='extra_flag_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='is_similar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='similar_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
