# Generated by Django 5.2.9 on 2026-01-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0014_articleinfo_extra_flag_bool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='article_type_pred',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='is_sentiment_llm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
