# Generated by Django 5.2.9 on 2026-02-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0015_articleinfo_article_type_pred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='NewsPaper_UploadDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
