# Generated by Django 5.2.9 on 2026-02-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0016_articleinfo_newspaper_uploaddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='is_municipal_commissioner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
