# Generated by Django 5.2.9 on 2026-05-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0017_articleinfo_is_municipal_commissioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='is_nhai',
            field=models.BooleanField(default=False),
        ),
    ]
